workflows:
  smartdms-pro-android-apk:
    name: WITHAQ PRO Phase 2
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate App Icon
        script: |
          dart run flutter_launcher_icons
      - name: Build APK Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mlm205383@gmail.com
